Add list components
openmsupply/unified-codes pull request #226
Opened 2020-10-11 23:30 UTC by wlthomson

Fixes #223.

## Description

Adds list components.

## Checklist:

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [ ] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [ ] Tests OK.

2020-10-11 23:54 UTC, katherine-sussol reviewed
Overall the changes to add the new components look good to me - unfortunately, I wasn't able to get the stories running because of a few import errors but I'm suspecting a later PR is going to fix this?

EDIT: Just saw PR #227 which I think answers my question!

2020-10-11 23:54 UTC, katherine-sussol commented on unified-codes/libs/ui/src/lib/components/data/atoms/List.stories.tsx
> +import { ArrowDownIcon, ArrowUpIcon, ArrowRightIcon } from '../../icons';
It looks like `ArrowDownIcon` and `ArrowRightIcon` might be in hiding? 🕵️‍♀️ 
They look newly added but I can't find them when loading up the PR - guessing they will be added in later PR?

2020-10-11 23:54 UTC, katherine-sussol commented on unified-codes/libs/ui/src/lib/components/data/atoms/List.stories.tsx
> +} from '@unified-codes/ui/components';
Have the exports been changed? Within the scope of this PR these aren't loading up (getting module not found errors)

2020-10-12 00:00 UTC, wlthomson commented
Note: thought I separated these PRs out cleanly, but looks like I didn't! Might need to review via #226 😢.

2020-10-12 03:18 UTC, mark-prins requested changes
ditto re Kat's comments. the stories for List doesn't load for me:
- the `ArrowDownIcon` and `ArrowRightIcon` haven't been added
- the path for other imports isn't working
- no `@unified-codes/ui/hooks` or `@unified-codes/ui/styles`

2020-10-12 03:18 UTC, mark-prins commented on unified-codes/libs/ui/src/lib/components/data/atoms/List.stories.tsx
> +} from '@unified-codes/ui/components';
Should this just be `./` ? These files are in the current folder.

2020-10-15 02:54 UTC, merged