#297 tidy up dgraph data
openmsupply/unified-codes pull request #305
Opened 2020-11-27 01:21 UTC by wlthomson

Fixes #297.

## Description

Updates dgraph data scripts.

## Checklist:

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [ ] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [ ] Tests OK.

2020-11-27 03:54 UTC, katherine-sussol reviewed
✨  Thanks for cleaning this up - much shinier and better structured now (typical 🐈 s - leaving a bit of a mess behind them)

It's mostly looking good - I haven't had a chance to go through everything in depth but dropped in a few notes with things I noticed today! Will look more next week.

2020-11-29 21:00 UTC, mark-prins reviewed
very impressive!
as noted, it needs some small changes to handle consumables.. and then can we run it and update the server?

2020-11-29 22:40 UTC, wlthomson commented on unified-codes/tools/scripts/dgraph/setup.sh
> +npx ts-node ./migration/v2/import.js ./data/v2/products.csv
6d274df3b858dfa2c49e32f68fdd5e9556d14316.

2020-11-29 23:01 UTC, katherine-sussol reviewed
Maybe for a later PR (separate issues?) - looks like we'll also need to revisit synonyms and properties at some stage. 

Unfortunately, seems we're a bit blocked on both atm 😿  
- Synonyms by Dgraph (which doesn't allow `@*` to search all languages in filter 🙀 )
- Properties by not having a spreadsheet with them filled in

Aside from that, once the consumables spawn some children I think everything else looks great 😎 🎉

2020-11-29 23:45 UTC, wlthomson commented on unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
> +            if (uc2 && uc3) {
Eep. 8aa5a305c70e87302e0efbaebf9dc2fbaaa2dc4b. Should do the job, but might be a few edge cases still missing?

2020-11-30 02:45 UTC, wlthomson commented on unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
> +                    for (let i = 0; i < entity.children.length && !hasCycle; i++) {
5c2064da7484f9b4c169cba39c3949d311af65a2 should do the job.

2020-11-30 02:45 UTC, wlthomson commented on unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
> +    public validateTree(): boolean {
5c2064da7484f9b4c169cba39c3949d311af65a2 🤓 .

2020-12-02 22:17 UTC, wlthomson commented
@katherine-sussol @mark-prins This should be backwards compatible with mSupply now!

2020-12-02 22:39 UTC, katherine-sussol requested changes
I'm sorry to be a huge pain 😿  - just gave it a test and noticed some nodes where I think they shouldn't be, haven't pinpointed the root cause yet but here's a screenshot:
![Screen Shot 2020-12-01 at 2 54 16 PM](https://user-images.githubusercontent.com/65875762/100939926-fe51c580-355b-11eb-9ec3-fb41691a0585.png)

2020-12-02 22:39 UTC, katherine-sussol commented on unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
> +                        const type = 'Strength';
`Strength`, or `DoseStrength`? (as per DgraphDataSource)?

2020-12-03 03:18 UTC, wlthomson commented on unified-codes/tools/scripts/dgraph/migration/v2/DataParser.ts
> +                        const type = 'Strength';
Oops. d0a7d7637e6c1b3b4b2e80456d0152b3ca3ad752.

2020-12-03 03:28 UTC, wlthomson commented
> I'm sorry to be a huge pain 😿 - just gave it a test and noticed some nodes where I think they shouldn't be, haven't pinpointed the root cause yet but here's a screenshot:
> ![Screen Shot 2020-12-01 at 2 54 16 PM](https://user-images.githubusercontent.com/65875762/100939926-fe51c580-355b-11eb-9ec3-fb41691a0585.png)

Hmm, looks like an error in the data... 

Lines `1075-1076`:

```
Verapamil,,,Oral,Tablet,Immediate-release,40mg,,,,,933f3f00,6331f543,ca50a600,dec4d100,77fcbb00,673c04bf,,,,,11170,,
Verapamil,,,Oral,Tablet,Immediate-release,80mg,,,,,933f3f00,6331f543,ca50a600,dec4d100,77fcbb00,673f04bf,,,,,11170,,
```

Note that `77fcbb00` is the code for the consumables category (it looks like the code has accidentally been reused for the `FormQualifier` entity for immediate-release Verapamil). The cycle detection is only on a per-category basis, so this slipped through the net. I wonder if I should add a placeholder root node above the categories to catch these sorts of things?

2020-12-03 04:10 UTC, wlthomson commented
@katherine-sussol Have added some code to detect duplicated for different entity types...

```
WARNING: Detected duplicate code 933f3f00!
WARNING: Detected duplicate code 888e7a00!
WARNING: Detected duplicate code 77fcbb00!
WARNING: Detected duplicate code 77fcbb00!
```

Think this explains what you're seeing!

2020-12-04 01:52 UTC, katherine-sussol approved these changes
![Dog LGTM Keyboard](https://media.giphy.com/media/kbVzENVNlE60MQR1HY/giphy.gif)
Thanks for the link to these GIFs, I will now use these for PRs.

2020-12-06 23:50 UTC, merged